/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef AUTO_OVERRIDE_NESTED_PREFAB_BAKE_CONFIG_H
#define AUTO_OVERRIDE_NESTED_PREFAB_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>

/* Headers of private dependencies */
#ifdef auto_override_nested_prefab_EXPORT
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if auto_override_nested_prefab_EXPORTS && (defined(_MSC_VER) || defined(__MINGW32__))
  #define AUTO_OVERRIDE_NESTED_PREFAB_EXPORT __declspec(dllexport)
#elif auto_override_nested_prefab_EXPORTS
  #define AUTO_OVERRIDE_NESTED_PREFAB_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
  #define AUTO_OVERRIDE_NESTED_PREFAB_EXPORT __declspec(dllimport)
#else
  #define AUTO_OVERRIDE_NESTED_PREFAB_EXPORT
#endif

#endif

