language: c

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

dist:
  - precise
  - trusty
  - xenial
  - bionic

osx_image:
  - xcode6.4
  - xcode11.2

install:
  - git clone https://github.com/SanderMertens/bake
  - make -C bake/build-$(uname)
  - bake/bake setup
  - bake

script:
  - bake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
