/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef CPPTEST_BAKE_CONFIG_H
#define CPPTEST_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#ifdef __BAKE__
#include <bake_util.h>
#endif
#include <bake_test.h>

/* Headers of private dependencies */
#ifdef CPPTEST_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef CPPTEST_STATIC
  #if CPPTEST_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define CPPTEST_EXPORT __declspec(dllexport)
  #elif CPPTEST_IMPL
    #define CPPTEST_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define CPPTEST_EXPORT __declspec(dllimport)
  #else
    #define CPPTEST_EXPORT
  #endif
#else
  #define CPPTEST_EXPORT
#endif

#endif

