/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SIMPLE_MODULE_BAKE_CONFIG_H
#define SIMPLE_MODULE_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>

/* Headers of private dependencies */
#ifdef SIMPLE_MODULE_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef SIMPLE_MODULE_STATIC
  #if SIMPLE_MODULE_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define SIMPLE_MODULE_EXPORT __declspec(dllexport)
  #elif SIMPLE_MODULE_IMPL
    #define SIMPLE_MODULE_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define SIMPLE_MODULE_EXPORT __declspec(dllimport)
  #else
    #define SIMPLE_MODULE_EXPORT
  #endif
#else
  #define SIMPLE_MODULE_EXPORT
#endif

#endif

