// Elie Wiese-Namir © 2025. All Rights Reserved.

#pragma once

#define SOLID_MACROS_VERSION_MAJOR 0
#define SOLID_MACROS_VERSION_MINOR 4
#define SOLID_MACROS_VERSION_PATCH 1
#define SOLID_MACROS_VERSION_BUILD 0

#define SOLID_MACROS_VERSION (SOLID_MACROS_VERSION_MAJOR * 1000000 + \
	SOLID_MACROS_VERSION_MINOR * 10000 + \
	SOLID_MACROS_VERSION_PATCH * 100 + \
	SOLID_MACROS_VERSION_BUILD)