/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef NOTEXPRESSION_BAKE_CONFIG_H
#define NOTEXPRESSION_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <reflecs>

/* Headers of private dependencies */
#ifdef NOTEXPRESSION_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if NOTEXPRESSION_IMPL && defined _MSC_VER
#define NOTEXPRESSION_EXPORT __declspec(dllexport)
#elif NOTEXPRESSION_IMPL
#define NOTEXPRESSION_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define NOTEXPRESSION_EXPORT __declspec(dllimport)
#else
#define NOTEXPRESSION_EXPORT
#endif

#endif

