#include "../private_api.h"

#ifdef FLECS_UNITS

typedef struct flecs_unit_definition_t {
    ecs_entity_t *id;
    const char *name;
    ecs_entity_t *parent;
    ecs_entity_t *quantity;
    ecs_entity_t *base;
    ecs_entity_t *over;
    ecs_entity_t *prefix;
    const char *symbol;
    const char *brief;
    ecs_primitive_kind_t kind;
    int32_t factor;
    int32_t power;
    bool is_prefix;
    bool is_quantity;
    bool is_unit;
    bool module;
} flecs_unit_definition_t;

static const flecs_unit_definition_t flecs_unit_definitions[] = {
    {&EcsUnitPrefixes, "prefixes",
        .module = true},
    {&EcsYocto, "Yocto",
        .is_prefix = true, .symbol = "y", .factor = 10,
        .power = -24},
    {&EcsZepto, "Zepto",
        .is_prefix = true, .symbol = "z", .factor = 10,
        .power = -21},
    {&EcsAtto, "Atto",
        .is_prefix = true, .symbol = "a", .factor = 10,
        .power = -18},
    {&EcsFemto, "Femto",
        .is_prefix = true, .symbol = "f", .factor = 10,
        .power = -15},
    {&EcsPico, "Pico",
        .is_prefix = true, .symbol = "p", .factor = 10,
        .power = -12},
    {&EcsNano, "Nano",
        .is_prefix = true, .symbol = "n", .factor = 10,
        .power = -9},
    {&EcsMicro, "Micro",
        .is_prefix = true, .symbol = "μ", .factor = 10,
        .power = -6},
    {&EcsMilli, "Milli",
        .is_prefix = true, .symbol = "m", .factor = 10,
        .power = -3},
    {&EcsCenti, "Centi",
        .is_prefix = true, .symbol = "c", .factor = 10,
        .power = -2},
    {&EcsDeci, "Deci",
        .is_prefix = true, .symbol = "d", .factor = 10,
        .power = -1},
    {&EcsDeca, "Deca",
        .is_prefix = true, .symbol = "da", .factor = 10,
        .power = 1},
    {&EcsHecto, "Hecto",
        .is_prefix = true, .symbol = "h", .factor = 10,
        .power = 2},
    {&EcsKilo, "Kilo",
        .is_prefix = true, .symbol = "k", .factor = 10,
        .power = 3},
    {&EcsMega, "Mega",
        .is_prefix = true, .symbol = "M", .factor = 10,
        .power = 6},
    {&EcsGiga, "Giga",
        .is_prefix = true, .symbol = "G", .factor = 10,
        .power = 9},
    {&EcsTera, "Tera",
        .is_prefix = true, .symbol = "T", .factor = 10,
        .power = 12},
    {&EcsPeta, "Peta",
        .is_prefix = true, .symbol = "P", .factor = 10,
        .power = 15},
    {&EcsExa, "Exa",
        .is_prefix = true, .symbol = "E", .factor = 10,
        .power = 18},
    {&EcsZetta, "Zetta",
        .is_prefix = true, .symbol = "Z", .factor = 10,
        .power = 21},
    {&EcsYotta, "Yotta",
        .is_prefix = true, .symbol = "Y", .factor = 10,
        .power = 24},
    {&EcsKibi, "Kibi",
        .is_prefix = true, .symbol = "Ki", .factor = 1024,
        .power = 1},
    {&EcsMebi, "Mebi",
        .is_prefix = true, .symbol = "Mi", .factor = 1024,
        .power = 2},
    {&EcsGibi, "Gibi",
        .is_prefix = true, .symbol = "Gi", .factor = 1024,
        .power = 3},
    {&EcsTebi, "Tebi",
        .is_prefix = true, .symbol = "Ti", .factor = 1024,
        .power = 4},
    {&EcsPebi, "Pebi",
        .is_prefix = true, .symbol = "Pi", .factor = 1024,
        .power = 5},
    {&EcsExbi, "Exbi",
        .is_prefix = true, .symbol = "Ei", .factor = 1024,
        .power = 6},
    {&EcsZebi, "Zebi",
        .is_prefix = true, .symbol = "Zi", .factor = 1024,
        .power = 7},
    {&EcsYobi, "Yobi",
        .is_prefix = true, .symbol = "Yi", .factor = 1024,
        .power = 8},
    {&EcsDuration, "Duration",
        .is_quantity = true,
        .brief = "Time amount (e.g. \"20 seconds\", \"2 hours\")"},
    {&EcsSeconds, "Seconds",
        .is_unit = true, .quantity = &EcsDuration, .symbol = "s",
        .kind = EcsF32,
        .brief = "Time amount in seconds"},
    {&EcsPicoSeconds, "PicoSeconds",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsSeconds, .prefix = &EcsPico, .kind = EcsF32},
    {&EcsNanoSeconds, "NanoSeconds",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsSeconds, .prefix = &EcsNano, .kind = EcsF32},
    {&EcsMicroSeconds, "MicroSeconds",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsSeconds, .prefix = &EcsMicro, .kind = EcsF32},
    {&EcsMilliSeconds, "MilliSeconds",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsSeconds, .prefix = &EcsMilli, .kind = EcsF32},
    {&EcsMinutes, "Minutes",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsSeconds, .symbol = "min", .factor = 60, .power = 1, .kind = EcsU32,
        .brief = "60 seconds"},
    {&EcsHours, "Hours",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsMinutes, .symbol = "h", .factor = 60, .power = 1, .kind = EcsU32,
        .brief = "60 minutes"},
    {&EcsDays, "Days",
        .is_unit = true, .quantity = &EcsDuration,
        .base = &EcsHours, .symbol = "d", .factor = 24, .power = 1, .kind = EcsU32,
        .brief = "24 hours"},
    {&EcsTime, "Time",
        .is_quantity = true,
        .brief = "Time passed since an epoch (e.g. \"5pm\", \"March 3rd 2022\")"},
    {&EcsDate, "Date",
        .is_unit = true, .quantity = &EcsTime, .kind = EcsU32,
        .brief = "Seconds passed since January 1st 1970"},
    {&EcsMass, "Mass",
        .is_quantity = true,
        .brief = "Units of mass (e.g. \"5 kilograms\")"},
    {&EcsGrams, "Grams",
        .is_unit = true, .quantity = &EcsMass, .symbol = "g",
        .kind = EcsF32},
    {&EcsKiloGrams, "KiloGrams",
        .is_unit = true, .quantity = &EcsMass, .base = &EcsGrams,
        .prefix = &EcsKilo, .kind = EcsF32},
    {&EcsElectricCurrent, "ElectricCurrent",
        .is_quantity = true,
        .brief = "Units of electrical current (e.g. \"2 ampere\")"},
    {&EcsAmpere, "Ampere",
        .is_unit = true, .quantity = &EcsElectricCurrent,
        .symbol = "A", .kind = EcsF32},
    {&EcsAmount, "Amount",
        .is_quantity = true,
        .brief = "Units of amount of substance (e.g. \"2 mole\")"},
    {&EcsMole, "Mole",
        .is_unit = true, .quantity = &EcsAmount, .symbol = "mol",
        .kind = EcsF32},
    {&EcsLuminousIntensity, "LuminousIntensity",
        .is_quantity = true,
        .brief = "Units of luminous intensity (e.g. \"1 candela\")"},
    {&EcsCandela, "Candela",
        .is_unit = true, .quantity = &EcsLuminousIntensity, .symbol = "cd", .kind = EcsF32},
    {&EcsForce, "Force",
        .is_quantity = true,
        .brief = "Units of force (e.g. \"10 newton\")"},
    {&EcsNewton, "Newton",
        .is_unit = true, .quantity = &EcsForce, .symbol = "N",
        .kind = EcsF32},
    {&EcsLength, "Length",
        .is_quantity = true,
        .brief = "Units of length (e.g. \"5 meters\", \"20 miles\")"},
    {&EcsMeters, "Meters",
        .is_unit = true, .quantity = &EcsLength, .symbol = "m",
        .kind = EcsF32},
    {&EcsPicoMeters, "PicoMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsPico, .kind = EcsF32},
    {&EcsNanoMeters, "NanoMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsNano, .kind = EcsF32},
    {&EcsMicroMeters, "MicroMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsMicro, .kind = EcsF32},
    {&EcsMilliMeters, "MilliMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsMilli, .kind = EcsF32},
    {&EcsCentiMeters, "CentiMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsCenti, .kind = EcsF32},
    {&EcsKiloMeters, "KiloMeters",
        .is_unit = true, .quantity = &EcsLength, .base = &EcsMeters,
        .prefix = &EcsKilo, .kind = EcsF32},
    {&EcsMiles, "Miles",
        .is_unit = true, .quantity = &EcsLength, .symbol = "mi",
        .kind = EcsF32},
    {&EcsPixels, "Pixels",
        .is_unit = true, .quantity = &EcsLength, .symbol = "px",
        .kind = EcsF32},
    {&EcsPressure, "Pressure",
        .is_quantity = true,
        .brief = "Units of pressure (e.g. \"1 bar\", \"1000 pascal\")"},
    {&EcsPascal, "Pascal",
        .is_unit = true, .quantity = &EcsPressure, .symbol = "Pa",
        .kind = EcsF32},
    {&EcsBar, "Bar",
        .is_unit = true, .quantity = &EcsPressure, .symbol = "bar",
        .kind = EcsF32},
    {&EcsSpeed, "Speed",
        .is_quantity = true,
        .brief = "Units of movement (e.g. \"5 meters/second\")"},
    {&EcsMetersPerSecond, "MetersPerSecond",
        .is_unit = true, .quantity = &EcsSpeed, .base = &EcsMeters,
        .over = &EcsSeconds, .kind = EcsF32},
    {&EcsKiloMetersPerSecond, "KiloMetersPerSecond",
        .is_unit = true, .quantity = &EcsSpeed,
        .base = &EcsKiloMeters, .over = &EcsSeconds, .kind = EcsF32},
    {&EcsKiloMetersPerHour, "KiloMetersPerHour",
        .is_unit = true, .quantity = &EcsSpeed,
        .base = &EcsKiloMeters, .over = &EcsHours, .kind = EcsF32},
    {&EcsMilesPerHour, "MilesPerHour",
        .is_unit = true, .quantity = &EcsSpeed, .base = &EcsMiles,
        .over = &EcsHours, .kind = EcsF32},
    {&EcsAcceleration, "Acceleration",
        .is_unit = true, .base = &EcsMetersPerSecond, .over = &EcsSeconds,
        .is_quantity = true, .quantity = &EcsAcceleration, .kind = EcsF32,
        .brief = "Unit of speed increase (e.g. \"5 meters/second/second\")"},
    {&EcsTemperature, "Temperature",
        .is_quantity = true,
        .brief = "Units of temperature (e.g. \"5 degrees Celsius\")"},
    {&EcsKelvin, "Kelvin",
        .is_unit = true, .quantity = &EcsTemperature,
        .symbol = "K", .kind = EcsF32},
    {&EcsCelsius, "Celsius",
        .is_unit = true, .quantity = &EcsTemperature,
        .symbol = "°C", .kind = EcsF32},
    {&EcsFahrenheit, "Fahrenheit",
        .is_unit = true, .quantity = &EcsTemperature,
        .symbol = "F", .kind = EcsF32},
    {&EcsData, "Data",
        .is_quantity = true,
        .brief = "Units of information (e.g. \"8 bits\", \"100 megabytes\")"},
    {&EcsBits, "Bits",
        .is_unit = true, .quantity = &EcsData, .symbol = "bit",
        .kind = EcsU64},
    {&EcsKiloBits, "KiloBits",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBits,
        .prefix = &EcsKilo, .kind = EcsU64},
    {&EcsMegaBits, "MegaBits",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBits,
        .prefix = &EcsMega, .kind = EcsU64},
    {&EcsGigaBits, "GigaBits",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBits,
        .prefix = &EcsGiga, .kind = EcsU64},
    {&EcsBytes, "Bytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBits,
        .symbol = "B", .factor = 8, .power = 1, .kind = EcsU64},
    {&EcsKiloBytes, "KiloBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsKilo, .kind = EcsU64},
    {&EcsMegaBytes, "MegaBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsMega, .kind = EcsU64},
    {&EcsGigaBytes, "GigaBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsGiga, .kind = EcsU64},
    {&EcsKibiBytes, "KibiBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsKibi, .kind = EcsU64},
    {&EcsMebiBytes, "MebiBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsMebi, .kind = EcsU64},
    {&EcsGibiBytes, "GibiBytes",
        .is_unit = true, .quantity = &EcsData, .base = &EcsBytes,
        .prefix = &EcsGibi, .kind = EcsU64},
    {&EcsDataRate, "DataRate",
        .is_quantity = true,
        .brief = "Units of data transmission (e.g. \"100 megabits/second\")"},
    {&EcsBitsPerSecond, "BitsPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsBits, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsKiloBitsPerSecond, "KiloBitsPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsKiloBits, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsMegaBitsPerSecond, "MegaBitsPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsMegaBits, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsGigaBitsPerSecond, "GigaBitsPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsGigaBits, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsBytesPerSecond, "BytesPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsBytes, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsKiloBytesPerSecond, "KiloBytesPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsKiloBytes, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsMegaBytesPerSecond, "MegaBytesPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsMegaBytes, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsGigaBytesPerSecond, "GigaBytesPerSecond",
        .is_unit = true, .quantity = &EcsDataRate,
        .base = &EcsGigaBytes, .over = &EcsSeconds, .kind = EcsU64},
    {&EcsPercentage, "Percentage",
        .is_quantity = true, .is_unit = true, .symbol = "%", .kind = EcsF32},
    {&EcsAngle, "Angle",
        .is_quantity = true,
        .brief = "Units of rotation (e.g. \"1.2 radians\", \"180 degrees\")"},
    {&EcsRadians, "Radians",
        .is_unit = true, .quantity = &EcsAngle, .symbol = "rad",
        .kind = EcsF32},
    {&EcsDegrees, "Degrees",
        .is_unit = true, .quantity = &EcsAngle, .symbol = "°",
        .kind = EcsF32},
    {&EcsColor, "Color",
        .is_quantity = true},
    {&EcsColorRgb, "Rgb",
        .parent = &EcsColor, .is_unit = true, .quantity = &EcsColor},
    {&EcsColorHsl, "Hsl",
        .parent = &EcsColor, .is_unit = true, .quantity = &EcsColor},
    {&EcsColorCss, "Css",
        .is_unit = true, .quantity = &EcsColor, .kind = EcsString},
    {&EcsBel, "Bel",
        .is_unit = true, .symbol = "B", .kind = EcsF32},
    {&EcsDeciBel, "DeciBel",
        .is_unit = true, .base = &EcsBel, .prefix = &EcsDeci, .kind = EcsF32},
    {&EcsFrequency, "Frequency",
        .is_quantity = true,
        .brief = "The number of occurrences of a repeating event per unit of time."},
    {&EcsHertz, "Hertz",
        .is_unit = true, .quantity = &EcsFrequency,
        .symbol = "Hz", .kind = EcsF32},
    {&EcsKiloHertz, "KiloHertz",
        .parent = &EcsFrequency, .is_unit = true, .base = &EcsHertz, .prefix = &EcsKilo,
        .kind = EcsF32},
    {&EcsMegaHertz, "MegaHertz",
        .parent = &EcsFrequency, .is_unit = true, .base = &EcsHertz, .prefix = &EcsMega,
        .kind = EcsF32},
    {&EcsGigaHertz, "GigaHertz",
        .parent = &EcsFrequency, .is_unit = true, .base = &EcsHertz, .prefix = &EcsGiga,
        .kind = EcsF32},
    {&EcsUri, "Uri",
        .is_quantity = true,
        .brief = "Universal resource identifier."},
    {&EcsUriHyperlink, "Hyperlink",
        .is_unit = true, .quantity = &EcsUri, .kind = EcsString},
    {&EcsUriImage, "Image",
        .is_unit = true, .quantity = &EcsUri, .kind = EcsString},
    {&EcsUriFile, "File",
        .is_unit = true, .quantity = &EcsUri, .kind = EcsString},
};

void FlecsUnitsImport(
    ecs_world_t *world)
{
    ECS_MODULE(world, FlecsUnits);
    ECS_IMPORT(world, FlecsMeta);
    ecs_set_name_prefix(world, "Ecs");

    int32_t count = sizeof(flecs_unit_definitions) /
        sizeof(flecs_unit_definitions[0]);
    for (int32_t i = 0; i < count; i ++) {
        const flecs_unit_definition_t *def = &flecs_unit_definitions[i];
        ecs_entity_t parent = ecs_id(FlecsUnits);
        if (def->parent) {
            parent = *def->parent;
        } else if (def->quantity && def->quantity != def->id) {
            parent = *def->quantity;
        } else if (def->is_prefix) {
            parent = EcsUnitPrefixes;
        }
        ecs_entity_t entity = *def->id = ecs_entity(world, {
            .name = def->name, .parent = parent
        });
        if (def->module) {
            ecs_add_id(world, entity, EcsModule);
        }
        if (def->is_quantity) {
            ecs_quantity_init(world, &(ecs_entity_desc_t){.id = entity});
        }
        if (def->is_prefix) {
            ecs_unit_prefix_init(world, &(ecs_unit_prefix_desc_t){
                .entity = entity, .symbol = def->symbol,
                .translation = {def->factor, def->power}
            });
        }
        if (def->is_unit) {
            ecs_unit_init(world, &(ecs_unit_desc_t){
                .entity = entity, .symbol = def->symbol,
                .quantity = def->quantity ? *def->quantity : 0,
                .base = def->base ? *def->base : 0,
                .over = def->over ? *def->over : 0,
                .prefix = def->prefix ? *def->prefix : 0,
                .translation = {def->factor, def->power}
            });
        }
        if (def->kind) {
            ecs_primitive_init(world, &(ecs_primitive_desc_t){
                .entity = entity, .kind = def->kind
            });
        }
    }

#ifdef FLECS_DOC
    ECS_IMPORT(world, FlecsDoc);
    for (int32_t i = 0; i < count; i ++) {
        const flecs_unit_definition_t *def = &flecs_unit_definitions[i];
        if (def->brief) {
            ecs_doc_set_brief(world, *def->id, def->brief);
        }
    }
#endif
}

#endif
