// Elie Wiese-Namir © 2025. All Rights Reserved.

#pragma once

#include "Versioning/SolidMacrosVersion.h"

#define EXPECTED_SOLID_MACROS_MAJOR 0
#define EXPECTED_SOLID_MACROS_MINOR 4
#define EXPECTED_SOLID_MACROS_PATCH 1
#define EXPECTED_SOLID_MACROS_BUILD 0

#define EXPECTED_SOLID_MACROS_VERSION (EXPECTED_SOLID_MACROS_MAJOR * 1000000 + \
	EXPECTED_SOLID_MACROS_MINOR * 10000 + \
	EXPECTED_SOLID_MACROS_PATCH * 100 + \
	EXPECTED_SOLID_MACROS_BUILD)

#define UNREAL_FLECS_VERSION_MAJOR 0
#define UNREAL_FLECS_VERSION_MINOR 6
#define UNREAL_FLECS_VERSION_PATCH 1
#define UNREAL_FLECS_VERSION_BUILD 2

#define UNREAL_FLECS_VERSION (UNREAL_FLECS_VERSION_MAJOR * 1000000 + \
	UNREAL_FLECS_VERSION_MINOR * 10000 + \
	UNREAL_FLECS_VERSION_PATCH * 100 + \
	UNREAL_FLECS_VERSION_BUILD)

