// Elie Wiese-Namir © 2025. All Rights Reserved.

#pragma once

#include "Versioning/SolidMacrosVersion.h"

#define EXPECTED_SOLID_MACROS_MAJOR 0
#define EXPECTED_SOLID_MACROS_MINOR 1
#define EXPECTED_SOLID_MACROS_PATCH 2
#define EXPECTED_SOLID_MACROS_BUILD 0

#define EXPECTED_SOLID_MACROS_VERSION (EXPECTED_SOLID_MACROS_MAJOR * 1000000 + \
	EXPECTED_SOLID_MACROS_MINOR * 10000 + \
	EXPECTED_SOLID_MACROS_PATCH * 100 + \
	EXPECTED_SOLID_MACROS_BUILD)

