/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FILTER_ITER_BAKE_CONFIG_H
#define FILTER_ITER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>

/* Headers of private dependencies */
#ifdef FILTER_ITER_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef FILTER_ITER_STATIC
  #if FILTER_ITER_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define FILTER_ITER_EXPORT __declspec(dllexport)
  #elif FILTER_ITER_IMPL
    #define FILTER_ITER_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define FILTER_ITER_EXPORT __declspec(dllimport)
  #else
    #define FILTER_ITER_EXPORT
  #endif
#else
  #define FILTER_ITER_EXPORT
#endif

#endif

