/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef BULK_ADD_REMOVE_BAKE_CONFIG_H
#define BULK_ADD_REMOVE_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>

/* Headers of private dependencies */
#ifdef BULK_ADD_REMOVE_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef BULK_ADD_REMOVE_STATIC
  #if BULK_ADD_REMOVE_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define BULK_ADD_REMOVE_EXPORT __declspec(dllexport)
  #elif BULK_ADD_REMOVE_IMPL
    #define BULK_ADD_REMOVE_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define BULK_ADD_REMOVE_EXPORT __declspec(dllimport)
  #else
    #define BULK_ADD_REMOVE_EXPORT
  #endif
#else
  #define BULK_ADD_REMOVE_EXPORT
#endif

#endif

