/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef RANDOMPLACEMENT_BAKE_CONFIG_H
#define RANDOMPLACEMENT_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <reflecs>

/* Headers of private dependencies */
#ifdef RANDOMPLACEMENT_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if RANDOMPLACEMENT_IMPL && defined _MSC_VER
#define RANDOMPLACEMENT_EXPORT __declspec(dllexport)
#elif RANDOMPLACEMENT_IMPL
#define RANDOMPLACEMENT_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define RANDOMPLACEMENT_EXPORT __declspec(dllimport)
#else
#define RANDOMPLACEMENT_EXPORT
#endif

#endif

