/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef API_BAKE_CONFIG_H
#define API_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#ifdef __BAKE__
#include <bake_util.h>
#endif
#include <bake_test.h>

/* Headers of private dependencies */
#ifdef api_EXPORT
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#if api_EXPORTS && (defined(_MSC_VER) || defined(__MINGW32__))
  #define API_EXPORT __declspec(dllexport)
#elif api_EXPORTS
  #define API_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
  #define API_EXPORTS __declspec(dllimport)
#else
  #define API_EXPORT
#endif

#endif

