name: build

on: [ push, pull_request ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    strategy:
      fail-fast: false
      matrix:
        cc: [ gcc-7, gcc-8, gcc-9, gcc-10, clang-8, clang-9, clang-10 ]
        cxx: [ g++-7, g++-8, g++-9, g++-10, clang++-8, clang++-9, clang++-10 ]

    steps:
      - uses: actions/checkout@v2
      - name: Install gcc
        run: |
          sudo apt-get install -y $${{ matrix.cc }}
          sudo apt-get install -y $${{ matrix.cxx }}
      
      - name: Install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          make -C bake/build-$(uname)
          bake/bake setup

      - name: Build Flecs
        run: |
          bake --strict
          bake --strict --cfg release

      - name: Build examples
        run: |
          bake examples/c --strict
          bake examples/cpp --strict
          bake examples/c --strict --cfg release
          bake examples/cpp --strict --cfg release
