name: build

on: [ push, pull_request ]

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    strategy:
      fail-fast: false
      matrix:
        compiler: |
          - cc: gcc-7
            cxx: g++7
          - cc: gcc-8
            cxx: g++8
          - cc: gcc-9
            cxx: g++9
          - cc: gcc-10
            cxx: g++10
          - cc: clang-8
            cxx: clang++-8
          - cc: clang-9
            cxx: clang++-9
          - cc: clang-10
            cxx: clang++-10

    steps:
      - uses: actions/checkout@v2
      - name: install compiler
        run: |
          sudo apt-get install -y ${{ matrix.compiler.cc }}
          sudo apt-get install -y ${{ matrix.compiler.cxx }}
      
      - name: install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          make -C bake/build-$(uname)
          bake/bake setup

      - name: build flecs
        run: |
          bake --strict
          bake --strict --cfg release

      - name: build examples
        run: |
          bake examples/c --strict
          bake examples/cpp --strict
          bake examples/c --strict --cfg release
          bake examples/cpp --strict --cfg release
